### ISSUE TITLE
Add support for Windows LPCWSTR (wchar_t const *) path

### ISSUE THREAD

**Issue by ypujante** [emilk/loguru#100]
First, thanks for the library. I have been using it extensively in my project (https://github.com/pongasoft/jamba) and it is very well done.

I do have a request for the `add_file` api which at the moment requires a path to be a `char const *` even for Windows. In Windows, the file APIs sometimes use a different type. 

For example, if you use the `GetTempPath` API to retrieve the temporary folder in which you could write log files, as described in the Windows [documentation](https://docs.microsoft.com/en-us/windows/desktop/FileIO/creating-and-using-a-temporary-file) page, the path returned is `TCHAR` which can be a `wchar_t` if the platform supports unicode (and from my own experience, on my Windows 10 machine, that is the case). The variable `lpTempPathBuffer` used in the API call is a `TCHAR const *`.

I assume one of the reason for doing this is that the temporary folder is usually something like `C:\Users\<Username>\AppData\Temp` where obviously `<Username>` could be anything, not necessarily simple ASCII characters. And converting this path to a `char const *` can generate an invalid path name.

I am also using the `libsndfile` library which has [implemented it this way](https://github.com/erikd/libsndfile/blob/1.0.28/src/sndfile.hh#L85):

```
SndfileHandle (const char *path, int mode = SFM_READ, int format = 0, int channels = 0, int samplerate = 0) ;
// ...
#ifdef ENABLE_SNDFILE_WINDOWS_PROTOTYPES
SndfileHandle (LPCWSTR wpath, int mode = SFM_READ, int format = 0, int channels = 0, int samplerate = 0) ;
// ...
#endif
```

They essentially have an overloaded method, so that if `TCHAR` is `char` then the "standard" call is used. But if `TCHAR` is actually `wchar_t` then it can use the other one ( `LPCWSTR` is really `wchar_t const *`)

Thanks
Yan

**Comment by emilk** [comment]
The wide paths in Windows are horrible. Working around them is a pain I do not want to relive. Microsoft should add proper UTF-8 support so that this pain can go away.

In the meantime, you can use a custom callback to log to some weird windows path: https://emilk.github.io/loguru/index.html#callbacks/loggingcallbacks
