### ISSUE TITLE
LOG(ERROR) output of slurm has special charactors

### ISSUE THREAD

**Issue by aoyulong** [emilk/loguru#102]
Hi, I has integrated the loguru with my code recently and use [slurm](https://slurm.schedmd.com/) to submit jobs to our server, but the ouput file of slurm has some special charactors `^[`:
![qq 20190302170849](https://user-images.githubusercontent.com/3069790/53679899-4fd97a80-3d0e-11e9-9556-cf0c76ae7e8b.jpg)

What can I do?

**Comment by zao** [comment]
The junk you see are color control codes, intended to change the color and intensity of text in a terminal.

Regular loguru output to log files don't contain them, but it has an option `g_colorlogtostderr` (true by default) to output nicely coloured logs to stderr, intended for interactive viewing in a terminal.

SLURM captures stdout and stderr verbatim into files and the tool you use to view them doesn't interpret them.

If you're using `less` to view your logs, you can pass `-R` to interpret color codes. If you don't care about the colors, you should be able to tell loguru to not colorize terminal output in the first place.

**Comment by aoyulong** [comment]
> The junk you see are color control codes, intended to change the color and intensity of text in a terminal.
> 
> Regular loguru output to log files doesn't contain them, but it has an option `g_colorlogtostderr` (true by default) to output nicely coloured logs to stderr, intended for interactive viewing in a terminal.
> 
> SLURM captures stdout and stderr verbatim into files and the tool you use to view them doesn't interpret them.
> 
> If you're using `less` to view your logs, you can pass `-R` to interpret color codes. If you don't care about the colors, you should be able to tell loguru to not colorize terminal output in the first place.

Thanks for this detailed explanation. And I have turned off the option.
