### ISSUE TITLE
Request: support for OutputDebugString on windows

### ISSUE THREAD

**Issue by ruurdadema** [emilk/loguru#107]
When using oguru in a gui app on windows there is no logging output as the stderr stream is not directed to the output window. In this case we have to use [OutputDebugString](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363362(v=vs.85).aspx)  to get the logging directed to the output window.

Ever thought of implementing this in loguru?

**Comment by emilk** [comment]
Just use a callback for it! It is in the docs: https://emilk.github.io/loguru/index.html#callbacks/loggingcallbacks
