### ISSUE TITLE
rsyslog support?

### ISSUE THREAD

**Issue by TheChuckster** [emilk/loguru#11]
Any plans to add rsyslog so that logs are viewable in say Papertrail? It's just sending UDP packets.

**Comment by emilk** [comment]
This is outside the scope of core Loguru, but you can add on this functionality easily using `loguru::add_callback`:

``` C++
void log_to_rsyslog(void*, const loguru::Message& message)
{
	g_rsyslog->send_udp(message.filename, message.line, message.message);
}

...

loguru::add_callback("rsyslog", log_to_rsyslog, nullptr, loguru::Verbosity_MAX);
```

**Comment by TheChuckster** [comment]
That's amazing, thanks!!!
