### ISSUE TITLE
Any new release plan?

### ISSUE THREAD

**Issue by 7kbird** [emilk/loguru#110]
The last release is v2.0.0 on Oct 2, 2018. Is there any new release plan?

**Comment by emilk** [comment]
Not much have happened since then :)

I will release a 2.1.0 once https://github.com/emilk/loguru/pull/108 and https://github.com/emilk/loguru/pull/118 lands

**Comment by emilk** [comment]
Loguru 2.1.0 released: https://github.com/emilk/loguru/releases/tag/v2.1.0
