### ISSUE TITLE
[Mistake]: There is no header guard in loguru.hpp 

### ISSUE THREAD

**Issue by Milerius** [emilk/loguru#111]
This is really dangearous ....  

This header file should contain a header guard to prevent multiple inclusion.

**Comment by emilk** [comment]
There are headers guards. Two of them, for two separate sections: `LOGURU_HAS_DECLARED_FORMAT_HEADER` and `LOGURU_HAS_DECLARED_STREAMS_HEADER`.

Having two allows you to `#include` `loguru.hpp` once without `LOGURU_WITH_STREAMS` defined and then once again with `LOGURU_WITH_STREAMS` defined without problems.
