### ISSUE TITLE
[Mistake]: Missing virtual destructor

### ISSUE THREAD

**Issue by Milerius** [emilk/loguru#112]
<img width="1205" alt="Capture d’écran 2019-08-17 à 10 58 24" src="https://user-images.githubusercontent.com/21139416/63209186-117a2100-c0de-11e9-826d-caa5dde17a95.png">

-> https://devblogs.microsoft.com/oldnewthing/?p=39443

**Comment by emilk** [comment]
Intentional. There is no need for a virtual destructor since all instances of `EcEntryData` are statically allocated and destroyed.
