### ISSUE TITLE
Don't overwrite main thread name in ::init()

### ISSUE THREAD

**Issue by Qix-** [emilk/loguru#117]
Is there a reason why the main thread name is overwritten when calling `::init()`? Could this be removed, or an option passed to `::init()` that sets it? Right now, setting the thread name prior to `::init()` makes no difference since it's overwritten. Seems like very odd behavior.

**Comment by emilk** [comment]
For me it is a matter of convenience – I want a clear readable name of the main thread. Most often I call `loguru::init` as the very first thing in  `main`. Maybe you can set your own thread name AFTER calling `loguru::init`?

`loguru::init` actually checks that there isn't already a name set. It only sets the thread name if there is no previous name set. BUT that is only implemented on some platforms. Maybe you can add an implementation of that for your platform and make a PR?
