### ISSUE TITLE
Usage of PATH_MAX constant requires <linux/limits.h> to be included on linux

### ISSUE THREAD

**Issue by ususdei** [emilk/loguru#14]

**Comment by emilk** [comment]
Fixed in https://github.com/emilk/loguru/pull/13

**Comment by bjoernpollex** [comment]
Actually I think this is more complicated to get right, I've described the problem in #16. I'll look into it a bit more and propose a solution.

**Comment by emilk** [comment]
#16 is hopefully resolved now - please take a look!
