### ISSUE TITLE
Use the Unlicense

### ISSUE THREAD

**Issue by ba32107** [emilk/loguru#142]
Hi!

Thanks very much for your work, I am planning to use this library in my own project. I was looking for your license details to see if it's compatible with my software. The README says the software is in the public domain, which is good news for me. However, this fact wasn't immediately straightforward for me, as I was looking for a LICENSE file right away.

I recommend putting in an explicit UNLICENSE file with The Unlicense text:
https://choosealicense.com/licenses/unlicense/

**Comment by oturpe** [comment]
I am involved with maintaining the DOSBox Staging package in Fedora Linux.
DOSBox Staging uses (a bundled copy of) Loguru.
Recently, Fedora moved to using SPDX identifiers in package License tags,
and at the same time, the set of allowed licenses was changed.
One change was that ["Public domain" is not allowed anymore][pd].
Rather, all public domain -like licenses must go through license review.
I am now submitting Loguru's license statement to that review.

Fedora license review also includes submitting licenses not known to SPDX to their review,
so I am doing that also.
[SPDX license inclusion principles] have this entry
"The license steward supports or is at least aware of and does not oppose its submission to the SPDX License List."
Thus, I notify @emilk that the license statement is entering that review,
and ask to state the support (or lack of) for inclusion in SPDX's database.

[pd]: https://docs.fedoraproject.org/en-US/legal/license-field/#_public_domain
[SPDX license inclusion principles]: https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md

Back to original issue:
If Loguru used a well known free & open source license,
such as the Unlicense as proposed in this issue,
hurdles like this could be avoided and Loguru would be easier to use.

**Comment by oturpe** [comment]
Thank you for allowing Unlicense!
I understand that if you just want to release to public domain,
tinkering with licensing isn't what you want to do.
But, distribution policies and laws of different countries are what they are.
