### ISSUE TITLE
Inherit ERROR_CONTEXT for new threads

### ISSUE THREAD

**Issue by rasmusgo** [emilk/loguru#15]
The ERROR_CONTEXT information is stored per thread and is not copied to new threads. This makes it harder to debug code with parallelization. I would like to be able to copy/access the error context from the parent thread to/in new threads to make debugging easier.

**Comment by emilk** [comment]
Fixed in b61cd4c6c462f666b1a56b0be84b3044d52c2eb2

``` C++
void foo(const char* parameter)
{
	ERROR_CONTEXT("parameter", parameter)
	const auto parent_ec_handle = loguru::get_thread_ec_handle();

	std::thread([=]{
		loguru::set_thread_name("child thread");
		ERROR_CONTEXT("parent context", parent_ec_handle);
		dangerous_code();
	}.join();
}
```
