### ISSUE TITLE
Problems with PATH_MAX

### ISSUE THREAD

**Issue by bjoernpollex** [emilk/loguru#16]
Loguru doesn't compile on Debian Jessie with g++ 4.9.2 because `PATH_MAX` isn't defined. I have a basic fix [here][1] (it has a typo, `MAX_PATH` instead of `PATH_MAX`). It also doesn't compile with g++ 5.3 on Mac OS X, because that requires to include `limits.h` to get `PATH_MAX`.

I would propose the following solution:

1. When in a POSIX environment, include `limits.h` first.
2. If `PATH_MAX` is not defined yet, and it is a Linux environment, include `linux/limits.h`
3. If that didn't work, manually define `PATH_MAX` to a reasonable default, e.g. 1024.

The most important point here I think is to have a default to fallback on, because apparently, `PATH_MAX` is [not reliable at all][2].

[1]: https://github.com/bjoernpollex/loguru/commit/09e981f83fe0015e799e8e535fca7756ca421d8a
[2]: http://stackoverflow.com/questions/833291/is-there-an-equivalent-to-winapis-max-path-under-linux-unix

**Comment by emilk** [comment]
This should be fixed in 6e0f221790e522205c513ccd8db97b4ba4b6a288 - please verify when you have the chance! I'll leave the issue open until then.

**Comment by emilk** [comment]
ping @bjoernpollex

**Comment by emilk** [comment]
I'll close this until I hear otherwise!

**Comment by bjoernpollex** [comment]
Sorry for the late response, I've been distracted by "important work". The issue is indeed fixed for me, thanks a lot.

**Comment by emilk** [comment]
No worries, thanks for reporting it!
