### ISSUE TITLE
Is there a specification of the log format?

### ISSUE THREAD

**Issue by fischerjulian** [emilk/loguru#165]
As a devop I would like to read logs, written by Loguru, with a log-collector such as Fluentd. In order to support enhanced log-analytics it is important that the Log-collector knows how to parse the log-entries.

Question 1: Are log-entries generated by loguru compatible with any standard C++ logging library for which a fluentd plugin might already exist?

Question 2: If Q1 is not applicable. Is there a description of the log format? E.g. a RegEx with documentation?

**Comment by emilk** [comment]
There is no formal specification, but it should be pretty easy to parse. One of the original design goals was to make it easy to grep the log files.

**Comment by fischerjulian** [comment]
Thank you.
