### ISSUE TITLE
How to change time format for file as well as for display?

### ISSUE THREAD

**Issue by MikeMaxNow** [emilk/loguru#168]
I am beginner and I really searched the docs, but I don't understand this. Can you help me?

- How can I change the time format (and **only** the time format) for the file as well as for the display? I want the keep the colors and everything else in their default format.
- How can I only show certain levels in the display, while saving all levels in the file?

I tried to create additional handlers, but then I loose the default format and I find it hard to recreate that.

**Comment by noamyogev84** [comment]
Is there any quick how-to regarding formatting? it's not clear
