### ISSUE TITLE
Errors in the documentation

### ISSUE THREAD

**Issue by knadh** [emilk/loguru#21]
add_file() with just these two params is not defined. It requires the 3rd verbosity param.
```
// Put every log message in "everything.log":
loguru::add_file("everything.log", loguru::Append);
```

Here, `loguru::INFO` doesn't work but `loguru::Verbosity_INFO` does.
```
// Only log INFO, WARNING, ERROR and FATAL to "latest_readable.log":
loguru::add_file("latest_readable.log", loguru::Truncate, loguru::INFO);
```

Thanks for the library!

**Comment by emilk** [comment]
Thanks, fixed in 4d6b54b1787c1eb51d9719714b2eecc284ee787a!
