### ISSUE TITLE
VS v140 narrowing conversion

### ISSUE THREAD

**Issue by Subtixx** [emilk/loguru#29]
First, thanks for this awesome logging library. This is exactly what I needed. Although it required some manual patching to get the deprecation warnings and ISO C stuff sorted out. (http://pastebin.com/gRSSeuvv), since this is not about the deprecation warnings I left them out and just pastebinned them.

The real "issue" is this error:
> error C2398: Element '3': conversion from 'long' to 'unsigned int' requires a narrowing conversion

which originates from here:
```
#define VLOG_SCOPE_F(verbosity, ...)                                                               \
	loguru::LogScopeRAII LOGURU_ANONYMOUS_VARIABLE(error_context_RAII_) =                          \
	((verbosity) > loguru::current_verbosity_cutoff()) ? loguru::LogScopeRAII() :                  \
	loguru::LogScopeRAII{verbosity, __FILE__, __LINE__, __VA_ARGS__}
```

Adding a C Style cast to `__LINE__` fixes the problem though.

```
#define VLOG_SCOPE_F(verbosity, ...)                                                               \
	loguru::LogScopeRAII LOGURU_ANONYMOUS_VARIABLE(error_context_RAII_) =                          \
	((verbosity) > loguru::current_verbosity_cutoff()) ? loguru::LogScopeRAII() :                  \
	loguru::LogScopeRAII{verbosity, __FILE__, (unsigned int)__LINE__, __VA_ARGS__}
```

**Comment by emilk** [comment]
Should be fixed in 4886bbe2f4bb58225c813d59789a2818dc6124eb. Thanks for your contribution!
