### ISSUE TITLE
unicode support

### ISSUE THREAD

**Issue by sailfish009** [emilk/loguru#32]
Hi, i want that loguru support unicode.

```
#define LOG_INFO(...)    LOG_F(INFO, __VA_ARGS__)
void function(const std::wstring& fn)
{
  LOG_INFO(" %s file opened\n", fn);                 // not work
  LOG_INFO(" %s file opened\n", fn.c_str());         // not work
 
  std::string str(fn.begin(), fn.end());
  LOG_INFO(" %s file opened\n", str.c_str());        // work
}
```

**Comment by emilk** [comment]
Loguru fully supports Unicode as long as it is UTF-8 encoded in a `const char*` or `std::string`.

If you are writing a unicode-aware app you should consider switching to UTF-8 encoded in `std::string`! `std::wstring` is in my opinion a pretty bad idea, and I don't want to complicate Loguru by supporting it! If you want to use it, just do this:

`LOG_S(INFO) << wstring2utf8(your_wstring);`
