### ISSUE TITLE
customize layout?

### ISSUE THREAD

**Issue by bl4ck5un** [emilk/loguru#33]
loguru has been working great for me (👍). I'm wondering if you plan to support custom output layout. E.g. Sometimes thread names are not needed.

**Comment by emilk** [comment]
You can already do some customization, e.g. try `#define LOGURU_THREADNAME_WIDTH 0` before you include `loguru.hpp`. Full custom layout is not something I plan on, but if you can come up with an elegant way to achieve it, I might reconsider!
