### ISSUE TITLE
rotating log

### ISSUE THREAD

**Issue by sailfish009** [emilk/loguru#38]
Hi, it would be good if loguru supports keep constant log file size, 

but update log in the file, like spdlog's rotate logger:

```
        // Create a file rotating logger with 5mb size max and 3 rotated files
        auto rotating_logger = spd::rotating_logger_mt("some_logger_name", "logs/mylogfile", 1048576 * 5, 3);
        for (int i = 0; i < 10; ++i)
            rotating_logger->info("{} * {} equals {:>10}", i, i, i*i);
```

**Comment by fidergo-stephane-gourichon** [comment]
From what I understand, the spirit of loguru is to just assume that an external program will rotate the logs by renaming the file. This might be more flexible that what you are considering. Check LOGURU_WITH_FILEABS in https://github.com/emilk/loguru#user-content-configuration-options

**Comment by emilk** [comment]
Indeed, please consider using [`logrotate`](https://linux.die.net/man/8/logrotate) or similar!
