### ISSUE TITLE
[Feature] toggle to enable and disable the preamble (filename and file line)

### ISSUE THREAD

**Issue by chipweinberger** [emilk/loguru#45]

**Comment by emilk** [comment]
You can use `RAW_LOG_F` for this, but there is currently no switch for it. I am, however, considering  adding more flags to control the preamble.

**Comment by emilk** [comment]
This is now supported in tag `v1.7.0`! Just do `loguru::g_preamble = false;` (e.g. right before `loguru::init`)

**Comment by chipweinberger** [comment]
Aw ya! Thanks! Great feature.
