### ISSUE TITLE
undefined symbol: _ZN6loguru24current_verbosity_cutoffEv

### ISSUE THREAD

**Issue by roman-minyaylov** [emilk/loguru#60]
Hi 
I have this error in Ubuntu, using logger in so library, loading library from Mono.

Have no ideas why.

**Comment by roman-minyaylov** [comment]
undefined reference to `loguru::current_verbosity_cutoff()'and so on during build... no sure what to do

**Comment by emilk** [comment]
Have you read the “Compiling” section in the README.md? In particular:

	#define LOGURU_IMPLEMENTATION 1
	#include <loguru.hpp>

**Comment by roman-minyaylov** [comment]
Yes, sorry, thank you.

In CMakeLists file with #define LOGURU_IMPLEMENTATION 1 was not included for LINUX platform. My fault.

**Comment by phlndrwd** [comment]
Sorry to revive an old thread, but I have a similar issue (with version 2.0, where LOGURU_IMPLEMENTATION isn't applicable).

With the following code:

```
#include <loguru.hpp>

int main(int argc, char** argv) {
    loguru::init(argc, argv);
    loguru::add_file("everything.log", loguru::Append, loguru::Verbosity_MAX);
    LOG_F(INFO, "Hello log file!");
    return 0;
}
```
Everything is fine. However, I'm trying to log with streams, so with the following tweak:

```
#define LOGURU_WITH_STREAMS 1

#include <loguru.hpp>

int main(int argc, char** argv) {
    loguru::init(argc, argv);
    loguru::add_file("everything.log", loguru::Append, loguru::Verbosity_MAX);
    LOG_S(INFO) << "Hello log file!";
    return 0;
}
```
I get errors stating 

> undefined reference to `loguru::StreamLogger::~StreamLogger()'

Any help?

**Comment by zao** [comment]
@phlndrwd You need to define `LOGURU_WITH_STREAMS` when compiling `loguru.cpp` as well, as it's gating optional features behind macros.

Consider supplying it as a compiler command line option for that TU or the whole project.

**Comment by phlndrwd** [comment]
That got it! Thank you @zao !
