### ISSUE TITLE
Does not work without RTTI 

### ISSUE THREAD

**Issue by tesch1** [emilk/loguru#61]
loguru.hpp:2218:30: error: cannot use
      typeid with -fno-rtti

**Comment by tesch1** [comment]
Nevermind.  Instead, maybe "LOGURU_RTTI" is not mentioned in the online documentation.

**Comment by emilk** [comment]
Yeah, the documentation is severely lacking – I'll maybe get to it on a dull day.

PR:s welcome ;)
