### ISSUE TITLE
Dynamic library

### ISSUE THREAD

**Issue by MunWolf** [emilk/loguru#67]
Hey,

I am using your logging system for my custom game engine, great work on the library btw.

But I am running into an issue when I create a dynamic version of my engine library because your log functions are not exported, would it be possible to create some definition to export the function declerations so they can be used outside the library?

**Comment by allisonvacanti** [comment]
Is there any interest in adding this? It's very necessary for loguru to be used in larger projects.

**Comment by emilk** [comment]
Fixed by merging of #79
