### ISSUE TITLE
Compilation failed on Windows

### ISSUE THREAD

**Issue by Gumichan01** [emilk/loguru#7]
I tested the demo program on Windows.
It cannot be compiled on this system.

On line 780 of *loguru.hpp* I have this following error:

    fatal error: dlfcn.h: No such file or directory

This kind of error also occurred with pthread.h.  
I used MinGW (g++ 4.7.1) on Windows 7. It does not provide these files. But is seems that Cygwin provides them (not tested).

Is there a way to make this library usable on windows with these compilers (g++, Visual C++, ...) without getting any dependencies?

**Comment by emilk** [comment]
Thanks for trying out Loguru on Windows - that's more than I have done =)

`pthread.h` is included whenever `_MSC_VER` is not defined - that should be an easy fix (e.g. only use pthreads on non-Windows).

`dlfcn.h` and friends is a bit harder - I need to find a set of `#define`:s which are set on linux, mac and cygwin, but not on msvc and mingw... I'll look into it!

**Comment by emilk** [comment]
Please try out 380c76e1fda1fcc46148b1cb4d75430b35ae3a05 and see how that works. I do not have access to a Windows computer right now which makes testing a bit difficult!

**Comment by Gumichan01** [comment]
I updated the file and I do not have these issues anymore.  
I cannot tell you if it really be compiled without any problems because the version of g++ provided by MinGW (4.7.1) does not have a complete C++11 support of  [concurrency] (https://gcc.gnu.org/gcc-4.7/cxx0x_status.html).  
I will use Clang to test the library.
