### ISSUE TITLE
Error contexts do not work on windows

### ISSUE THREAD

**Issue by allisonvacanti** [emilk/loguru#74]
Tested using segfaults, uncaught exceptions, and `abort`, none of the `ErrorContext` entries were printed on MSVC2015 x64.

**Comment by emilk** [comment]
This is the simplest test:

``` C
ERROR_CONTEXT("some_number", 42);
auto text = loguru::get_error_context();
printf("%s\n", text.c_str());
```

If that doesn't work, it is a bug. Maybe related to https://github.com/emilk/loguru/issues/43 ?

I don't have windows, so you're on your own!

**Comment by allisonvacanti** [comment]
Manually retrieving the error context does work, but without the signal handling it's not terribly useful. I think this is probably a known issue since the handlers aren't expected to work on windows.

I'll close this out since the problem is not really an error context issue.
