### ISSUE TITLE
ERR and WRN log lines not easily distinguishable because of identical colors

### ISSUE THREAD

**Issue by Weeena** [emilk/loguru#76]
My system: Ubuntu 18.04.1 LTS.

I would like to easily distinguish errors and warnings in the log lines on the terminal. However, ERR and WRN lines now have identical colors.

In loguru, color code 31 is used for warnings and 91 for errors (and fatal). These are the intended colors:
![2018-09-13_09h18_52](https://user-images.githubusercontent.com/19182442/45473021-22841a80-b736-11e8-9b29-55c40964dfe5.png)
The colors are distinguishable (although quite similar).

However, the ERR and WRN log lines in loguru not only have a color, they are also printed bold. This is how text is written on my terminal in bold:
![2018-09-13_09h23_40](https://user-images.githubusercontent.com/19182442/45473205-bfdf4e80-b736-11e8-82af-0f3d9fb026a4.png)
As you can see, the colors now are identical.

My suggestion to solve this problem would be to use a different color for WRN log entries. For me a perfect joice would be terminal_yellow() (color code 33) since this would be derived from the traffic light system and, thus, would be completely intuitive for me.

**Comment by emilk** [comment]
Good idea! Suggested fix: https://github.com/emilk/loguru/pull/81
