### ISSUE TITLE
Request for license adaptation for distribution.

### ISSUE THREAD

**Issue by SOesterreicher** [emilk/loguru#91]
Hello,
I discussed with my legal department the license enhancement regarding public domain usability in areas where public domain is not recognized. Thanks for having this point mentioned.
"This software is in the public domain. Where that dedication is not recognized, you are granted a perpetual, irrevocable license to copy and modify this file as you see fit."
Is it possible to add the distribution point to the enhancement to ensure we can distribute this code further. This could look like:
"This software is in the public domain. Where that dedication is not recognized, you are granted a perpetual, irrevocable license to copy, modify **and distribute** this file as you see fit."
Thanks in advance.
Siegfried Oesterreicher

**Comment by bugwelle** [comment]
Also isn't `this file` wrong as this library isn't header only anymore? :-)

**Comment by SOesterreicher** [comment]
Any news on this license enhancement request for "distribution".

Thanks in advance.
Siegfried Oesterreicher

**Comment by emilk** [comment]
Fixed in 0ef2eeae427a9f20510174d9451924f9d26b39e7

**Comment by SOesterreicher** [comment]
Thank you very much.
