### ISSUE TITLE
Stream function for skipping stack lines?

### ISSUE THREAD

**Issue by Qix-** [emilk/loguru#96]
It'd be great if I could do something like the following:

```c++
LOG_S(INFO) << loguru::skip_stack(1) << "some text";
```

The use-case here is that I often write `perror()`-like functions that aren't useful where `LOG_S` is being used but are instead important where the wrapper was called.

**Comment by emilk** [comment]
You can accomplish this by making you own macro:

``` C
void my_perror(const char* file, unsigned line)
{
    ...
    loguru::log(loguru::Verbosity_INFO, file, line, "some text");
}

#define MY_PERROR my_perror(__FILE__, __LINE__)
```

**Comment by emilk** [comment]
I agree it would be nice. The problem is that would require getting the file/line from the stacktrace which is slow, unreliable and not always available.

**Comment by emilk** [comment]
`loguru::stacktrace` takes a `skip` argument that does just this.

**Comment by Qix-** [comment]
Ah I see, you're not getting the backtrace for each logging invocation. Not sure why I had that in my head.

Thanks :)
